/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Durability {
  Fast = 0,
  Flush = 1
}
export const enum ErrorKind {
  Internal = 1,
  Usage = 2,
  NotFound = 3,
  AlreadyExists = 4,
  Busy = 5,
  Permission = 6,
  Corrupt = 7,
  Io = 8
}
export interface Lite3Frame {
  seq: bigint
  timestampNs: bigint
  flags: number
  payload: Buffer
}
export declare class Client {
  constructor(poolDir: string)
  createPool(poolRef: string, sizeBytes: number | bigint): Pool
  openPool(poolRef: string): Pool
  close(): void
}
export declare class Pool {
  appendJson(payload: Buffer, tags: Array<string>, durability: Durability): Buffer
  appendLite3(payload: Buffer, durability: Durability): bigint
  getJson(seq: number | bigint): Buffer
  getLite3(seq: number | bigint): Lite3Frame
  openStream(sinceSeq?: number | bigint | undefined | null, maxMessages?: number | bigint | undefined | null, timeoutMs?: number | bigint | undefined | null): Stream
  openLite3Stream(sinceSeq?: number | bigint | undefined | null, maxMessages?: number | bigint | undefined | null, timeoutMs?: number | bigint | undefined | null): Lite3Stream
  close(): void
}
export declare class Stream {
  nextJson(): Buffer | null
  close(): void
}
export declare class Lite3Stream {
  next(): Lite3Frame | null
  close(): void
}
export interface ReplayOptions {
  speed?: number
  sinceSeq?: number | bigint
  maxMessages?: number | bigint
  timeoutMs?: number | bigint
}
export function replay(pool: Pool, options?: ReplayOptions): AsyncGenerator<Buffer>
