/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Durability {
  Fast = 0,
  Flush = 1
}
export const enum ErrorKind {
  Internal = 1,
  Usage = 2,
  NotFound = 3,
  AlreadyExists = 4,
  Busy = 5,
  Permission = 6,
  Corrupt = 7,
  Io = 8
}
export declare class Client {
  constructor(poolDir: string)
  createPool(poolRef: string, sizeBytes: number | bigint): Pool
  openPool(poolRef: string): Pool
  close(): void
}
export declare class Pool {
  appendJson(payload: Buffer, descrips: Array<string>, durability: Durability): Buffer
  getJson(seq: number | bigint): Buffer
  openStream(sinceSeq?: number | bigint | undefined | null, maxMessages?: number | bigint | undefined | null, timeoutMs?: number | bigint | undefined | null): Stream
  close(): void
}
export declare class Stream {
  nextJson(): Buffer | null
  close(): void
}
